### ISSUE TITLE
Visualizations not shown

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/DataTaggingServer#54]
They are created on disk, but are not shown.

**Comment by michbarsinai** [comment]
Need to validate this.

**Comment by MorVilozni** [comment]
```
a.a.OneForOneStrategy - Cannot run program "C:\Program Files (x86)\Graphviz2.38\bin\dot.exe": error=2, No such file or directory
java.io.IOException: Cannot run program "C:\Program Files (x86)\Graphviz2.38\bin\dot.exe": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at actors.VisualizationActor.createDecisionGraphVisualizationFile(VisualizationActor.scala:79)
	at actors.VisualizationActor$$anonfun$receive$1.$anonfun$applyOrElse$1(VisualizationActor.scala:38)
	at actors.VisualizationActor$$anonfun$receive$1.$anonfun$applyOrElse$1$adapted(VisualizationActor.scala:37)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at actors.VisualizationActor$$anonfun$receive$1.applyOrElse(VisualizationActor.scala:37)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at actors.VisualizationActor.aroundReceive(VisualizationActor.scala:29)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at actors.VisualizationActor.createDecisionGraphVisualizationFile(VisualizationActor.scala:79)
	at actors.VisualizationActor$$anonfun$receive$1.$anonfun$applyOrElse$1(VisualizationActor.scala:38)
	at actors.VisualizationActor$$anonfun$receive$1.$anonfun$applyOrElse$1$adapted(VisualizationActor.scala:37)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at actors.VisualizationActor$$anonfun$receive$1.applyOrElse(VisualizationActor.scala:37)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)

```
